### ISSUE TITLE
End-of-Year approvals

### ISSUE THREAD

**Issue by ghost** [arcalot/arcalot-round-table#25]
## Please describe what you would like to see in this project

I have temporarily lowered the number of chairs required to merge a PR into this repository to 2 as I am on an extended leave until January 8. This needs to be reset once we resume normal operations.

**Comment by portante** [comment]
Why do we need to do that?  What is the harm in waiting until January 8th for your return?

**Comment by portante** [comment]
There are four chairs, one is on vacation, so now it goes from 4 to 2 required for approvals?

**Comment by portante** [comment]
Right.

So why do we need this change to the process?  It also means that only 2 chairs need to approve a non-chair proposed change.

Doesn't seem like a good idea to institute such a process change without the community agreeing to this.  You can split the community that way (not that that is likely to happen, but I don't think such a change is warranted).

**Comment by portante** [comment]
So only 2 chairs are required to approve any non-chair proposed amendment?  That was not my understanding.  Where is that documented?

**Comment by portante** [comment]
See the last sentence here: https://github.com/arcalot/arcalot-round-table/blob/main/CHARTER.md#changing-the-charter

This means that a change to the Charter can not be done without 66% of the chairs.

**Comment by portante** [comment]
I get the sentiment, but I think the github mechanisms are not able to help us enforce the safe-guards.

We should either require 1 chair to also approve a PR, and that chair is bound to ensure the right quorums are met, or we need to amend the CHARTER to include how the GitHub mechanisms will be used to help the voting process.

For now, I'd leave the original setting in place.  If a problem with it arises, we can review when you get back and straighten out how we want this to work in the future.

**Comment by portante** [comment]
As above, it seems that using various GitHub mechanisms to help "enforce" the voting policies needs refinement.

It seems like a mixed message to say "Chairs have admin permissions on GitHub any way, so they could, at any time, merge things without the required number of votes," and then also say this "will prevent any chair-initiated changes to be merged until I'm back."

Perhaps we could say that:

> The GitHub merge gates, or requirements, are used to ensure 2 chairs have properly reviewed a proposal to ensure it meets the required process approvals.  No chair should have to use their GitHub admin privileges to merge a proposal once approved.

This way we keep the GitHub mechanism away from the approval process, but use it to ensure the chairs enforce the process.

I can amend the CHARTER so that 2 is the number for the GitHub approval mechanism, and the Charter directs the process to be separate from the GitHub mechanism.

**Comment by portante** [comment]
> I personally wouldn't mix GitHub's mechanisms in here, they are inadequate to enforce the charter because if a chair proposes a change, two other chairs are required to merge, while if someone else proposes, only 2 chairs are required in total. The charter currently mandates that all decisions be voted for by 2/3rds of the chairs, so the number 2 as a strict enforcement isn't adequate to meet the charter requirements.
> 
> Given that chairs have administrative rights on all Arcalot properties, this isn't meant to, and cannot be the arbiter of charter enforcement. Making sure that the rules are met is the job of the chairs, technical mechanisms can only assist.

I agree.  That is what I am trying communicate.  I find that this change to a GitHub mechanism from 3 to 2 is confusing and sends the wrong message because it seems to say that the github mechanisms ARE used as part of the process.  But in your previous paragraph you say "they are inadequate to enforce the charter."

What I am trying to saying is that the process of the charter CANNOT include the mechanisms.

The process of merging a PR into the arcalot-round-table SHOULD use the mechanisms only to ensure that 2 chairs are reviewing the PR to ensure the process of the charter IS met.

As such, it should be left at 2, the current setting, and the CHARTER should be amended to describe explicitly what the github mechanisms are used for.

**Comment by dustinblack** [comment]
Closing as obsolete.
